---
- name: Setup Web Server
  hosts: all
  gather_facts: false

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
    - name: Start Nginx
      service:
        name: nginx
        state: started
    - name: Ensure /var/www/html
      file:
        path: /var/www/html/
        state: directory
    - name: Copy index.html
      copy:
        content: "<h1>Ahoj svete z {{ ansible_host }}!<h1>\n"
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
    - name: See
      debug:
        msg: "See: http://{{ ansible_host }}"
